title: Less is More.
author: Matthew Madden
email: matt@matthew-madden.com
description: > # this means to ignore newlines until "baseurl:"
  This site was born in an effort to learn GitHub better, by diving into an
  awesomely interactive course on creating GitHub pages with Jekyll. Thanks, GitHub!

# social links
twitter_username: @mattmaddenmusic
github_username:  MatthewMadden

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
